### ISSUE TITLE
Error with compilation hash

### ISSUE THREAD

**Issue by fgaston** [MarvelSQ/html-prefetch-css-webpack-plugin#2]
Instead of prefetching lazy.css as
<link rel="prefetch" href="lazy.css">

the plugin is prefetching the file withs its compilation.hash (e.j.: 123456789) and give the following link inside the html
<link rel="prefetch" href="lazy.css?123456789">

As a result when the browser is using lazy.css, the stylesheet is loaded again instead of retrieving it from the cache.

Solution:
Remove ?${compilation.hash} on the line 86 of the index.js

**Comment by fgaston** [comment]
No answer, just closing the issue ?!!

**Comment by MarvelSQ** [comment]
@fgaston Sorry for not responding to your issue. It's my fault. Thank you for the issue, the problem is because I did not do the corresponding test when I added the compilation.hash. 
this time，i add a simple test for this package。

Thanks again
